image: node:alpine

variables:
  PUBLIC_URL: /my-book-shelve

cache:
  paths:
    - node_modules

stages:
  - test

test_async:
  script:
    - yarn install
    - npm install -g json-server
    - yarn test
