image: node:alpine

variables:
  PUBLIC_URL: /my-book-shelve

cache:
  paths:
    - node_modules

stages:
  - test

test_async:
  script:
    - |
      apk add --update \
          python \
          python-dev \
          py-pip \
          build-base \
        && pip install virtualenv \
        && rm -rf /var/cache/apk/*
    - yarn install
    - npm install -g json-server
    - yarn test
