export const ACTION_NONE = 'ACTION_NONE';
export const ACTION_GOTO_ADD_BOOK = 'ACTION_GOTO_ADD_BOOK';
export const ACTION_ADD_BOOK = 'ACTION_ADD_BOOK';
export const ACTION_GOTO_LIST_BOOKS = 'ACTION_GOTO_LIST_BOOKS';
export const ACTION_LIST_BOOKS = 'ACTION_LIST_BOOKS';


export const ACTION_ASK_BOOK = 'ACTION_ASK_BOOK';
export const ACTION_CONFIRM_ASSIGN = 'ACTION_CONFIRM_ASSIGN';
export const ACTION_RETURN_BOOK = 'ACTION_RETURN_BOOK';
export const ACTION_CONFIRM_RETURN = 'ACTION_CONFIRM_RETURN';

export const ACTION_DELETE_BOOK = 'ACTION_DELETE_BOOK';

export const ACTION_GOTO_NOTIFICATIONS = 'ACTION_GOTO_NOTIFICATIONS';
export const ACTION_CONFIRM_RENTAL = 'CONFIRM_RENTAL';
export const ACTION_REJECT_RENTAL = 'REJECT_RENTAL';
