export default {
    BookActionConstant: {
        ACTION_ASK_BOOK: 'ACTION_ASK_BOOK',
        ACTION_CONFIRM_ASSIGN: 'ACTION_CONFIRM_ASSIGN',
        ACTION_RETURN_BOOK: 'ACTION_RETURN_BOOK',
        ACTION_CONFIRM_RETURN: 'ACTION_CONFIRM_RETURN',
        ACTION_DELETE_BOOK: 'ACTION_DELETE_BOOK',
        ACTION_REVIEW_BOOK: 'ACTION_REVIEW_BOOK',
        ACTION_GET_REVIEWS_FOR_BOOK: 'ACTION_GET_REVIEWS_FOR_BOOK',
    },
    NotificationActionConstant: {
        ACTION_CONFIRM_RENTAL: 'CONFIRM_RENTAL',
        ACTION_REJECT_RENTAL: 'REJECT_RENTAL',
        ACTION_GET_RETURNS: 'ACTION_GET_RETURNS',
    },
    SocialActionConstant: {
        ACTION_USER_DATA: 'ACTION_USER_DATA',
        ACTION_LOGIN_USER: 'ACTION_LOGIN_USER',
    },
    PageActionConstant: {
        ACTION_GOTO_SPACES: 'ACTION_GOTO_SPACES',
        ACTION_ADD_BOOK: 'ACTION_ADD_BOOK',
        ACTION_GOTO_LIST_BOOKS: 'ACTION_GOTO_LIST_BOOKS',
        ACTION_LIST_BOOKS: 'ACTION_LIST_BOOKS',
        ACTION_GOTO_NOTIFICATIONS: 'ACTION_GOTO_NOTIFICATIONS',
    },
};
