export const ACTION_ASK_BOOK = 'ACTION_ASK_BOOK';
export const ACTION_CONFIRM_ASSIGN = 'ACTION_CONFIRM_ASSIGN';
export const ACTION_RETURN_BOOK = 'ACTION_RETURN_BOOK';
export const ACTION_CONFIRM_RETURN = 'ACTION_CONFIRM_RETURN';

export const ACTION_DELETE_BOOK = 'ACTION_DELETE_BOOK';
