export default {
    MYBOOKSHELVE_ACTION_IN_PROGRESS: 'Action in progress...',
    MYBOOKSHELVE_OPERATION_FAILED: 'Operation failed.',
    MYBOOKSHELVE_STRING_NEW_BOOK_ADDED: 'New book was successfully added',
    MYBOOKSHELVE_STRING_BOOK_REMOVED: 'The book was successfully removed',
    MYBOOKSHELVE_STRING_CONFIRM: 'Confirm',
    FilteringTabsStrings: {
        MYBOOKSHELVE_STRING_RENTED: 'Rented',
        MYBOOKSHELVE_STRING_ASSIGNED: 'Assigned',
        MYBOOKSHELVE_STRING_ALL: 'All Space',
    },
    MYBOOKSHELVE_ADD_NEW_BOOK_BUTTON: '+',
    MYBOOKSHELVE_ADD_NEW_BOOK_TITLE: 'Add Book',
    MYBOOKSHELVE_PENDING_ASSIGNMENT: 'Pending assignment',
    MYBOOKSHELVE_INVALID_FIELDS: 'Invalid fields',
    MYBOOKSHELVE_RENTAL_SETTINGS: 'Rental settings',
    MYBOOKSHELVE_RENTAL_DURATION: 'Select rental duration',
    MYBOOKSHELVE_RATING_TITLE: 'Rate Book',
    MYBOOKSHELVE_RATING_STATE: 'Rate State',
    MYBOOKSHELVE_RATING_CONTENT: 'Rate Content',
    MYBOOKSHELVE_CUSTOMER_REVIEWS: 'customer reviews',
};
