export const ACTION_GOTO_ADD_BOOK = 'ACTION_GOTO_ADD_BOOK';
export const ACTION_ADD_BOOK = 'ACTION_ADD_BOOK';
export const ACTION_GOTO_LIST_BOOKS = 'ACTION_GOTO_LIST_BOOKS';
export const ACTION_LIST_BOOKS = 'ACTION_LIST_BOOKS';
export const ACTION_GOTO_NOTIFICATIONS = 'ACTION_GOTO_NOTIFICATIONS';
