export default {
    SpaceActionConstant: {
        FOLLOW_SPACE: 'ACTION_FOLLOW_SPACE',
        UNFOLLOW_SPACE: 'ACTION_UNFOLLOW_SPACE',
    },
    BookActionConstant: {
        ACTION_ADD_BOOK: 'ACTION_ADD_BOOK',
        ACTION_ASK_BOOK: 'ACTION_ASK_BOOK',
        ACTION_CONFIRM_ASSIGN: 'ACTION_CONFIRM_ASSIGN',
        ACTION_RETURN_BOOK: 'ACTION_RETURN_BOOK',
        ACTION_CONFIRM_RETURN: 'ACTION_CONFIRM_RETURN',
        ACTION_DELETE_BOOK: 'ACTION_DELETE_BOOK',
        ACTION_REVIEW_BOOK: 'ACTION_REVIEW_BOOK',
        ACTION_GET_REVIEWS_FOR_BOOK: 'ACTION_GET_REVIEWS_FOR_BOOK',
        ACTION_GET_BOOK_DESCRIPTION: 'ACTION_GET_BOOK_DESCRIPTION',
    },
    NotificationActionConstant: {
        ACTION_CONFIRM_RENTAL: 'CONFIRM_RENTAL',
        ACTION_RATE_RETURN: 'RATE_RETURN',
        ACTION_REJECT_RENTAL: 'REJECT_RENTAL',
        ACTION_GET_RETURNS: 'ACTION_GET_RETURNS',
        ACTION_GET_QUEUE: 'ACTION_GET_QUEUE',
    },
    SocialActionConstant: {
        ACTION_USER_DATA: 'ACTION_USER_DATA',
        ACTION_LOGIN_USER: 'ACTION_LOGIN_USER',
        ACTION_LOGOUT_USER: 'ACTION_LOGOUT_USER',
    },
    PageActionConstant: {
        ACTION_GOTO_LIST_SPACES: 'ACTION_GOTO_LIST_SPACES',
        ACTION_GOTO_LIST_BOOKS: 'ACTION_GOTO_LIST_BOOKS',
        ACTION_REFRESH_STATE: 'ACTION_REFRESH_STATE',
        ACTION_ADD_URL_PARAMS: 'ACTION_ADD_URL_PARAMS',
    },
};
